/**
 * 
 */
package logan;

import java.util.Stack;

/**
 * @author longphan
 *
 */
public class HackerRank_In_A_String {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		String s = "uvlmzncuebsfokklcfjnfgegzeocddsjmmonpegkdnyamgbgxefncfkxueyyopwgnigtxyeuipzxotklqjpdgqkuydektinwjqnzpylglmwjidnlbaiuxnxidtpxtnicwexgwidqxgqqoqmtnbqtpsfszxmuqjnytjxqmgkdwmgydinoujfzanowikkupznxfjbxkgnjjugwvapnyzpitzgbisaetxaofnfsveielfkudicxpmimewvdkdngtxadxpwkxtbqoqocaxzuwzdogdxjgbdxekefuyyujjfbkqdeivqdtdjfkklxzbdwtldxzkwmlncxiijbgmdgzbapsgjcpetuevdwlkbcxzjgfknmdynmqnkkqbjjpzykbftdmvppvvuuwgvpsdvetufqfoftbcdogowoaajvogdnqescazfkdpjzywzzyutjclajkdotxnpznetanqqbduycyjgjqijedeigepgdoqzmyoopnpbwwmcbevxdjvwtgisqpnttvylikuvdzjcndwbvvdvbwwxtjpovdngvpnslfzipupycoziobuolefyiqwwnwgbnswzuilbnskgxlqubwecsmzzppavxsnpewazcgbpqxpjxwjbmvdokkdeohuozvnkgjkuabsrjceoozqkxylibkogpxcusrpayfgaagmcxtpqpjpvtgyggtnjfqthuurylkyoehgzeugofmbqknjfrfrgerucxzjvnucymdylfkmdrrbvucnfveidmxcztbclqmrwfgrqsnrsxcmklngptggwliuyvnerazgecasibgcqwradqeseozmfcyeiutblizjawvoegkptvxoffcadaegdvahybxcsyzcjkfkqgqeypyzhuycrbylbzjdmnerlfesuubsobamnepaxinyfwmdefnpfldceaanlwypwqqgbezyaluahawckhbkmjsyxuauxamxhaosbyvfrznqldggokozyjayyyeyppdbmujorvxwkczybsvhgflisohzgterlqyllksohkcqdylijjpydqcksvxrgrvbchriaocwcenwkkwwtvrerrlpdqdtnlttruqcvbuzzqtvmniccazldsgonxcvgdzpwsamdoxrfhszetcepkbunulwaprbyvezybdvofbilwavjrmqqpyufcckhwowzzbnjqinzfvsyxuaobvnuvktwkmdbpeapxtucagfnqcruijknqllvpyukoawvhspvhcymxgexexeqijvgnpcmoiahpxedxkbaqcfrggczpbtcgpxmkqavyndoklovytllgaolxfxalidygctfsnxfmosveodjvvjtoixilxwpvleawwdxkkkbbppxvwawbtejbabqlemxlieukbsulbusppswyzpemjbpitltwzofkvkbstjptigtpucmzzpocazcwwjlzwvkvcxxtippbljnakezdoeegxfpvamxlftnqqkdsxpcmspkfpwituqdtkkllgvxzxceempsuqepaqjinusvadsxevgklgwaafejnkywjasdazedxicvnyktijjjveounydizcnkmbjvlkfafcpogbmzqsbsgyvysyypkyunfwegdbucykxbfcmewzjpkltbscqlkdvskzidcglcoastiuepdotznwcvwsydbckmjgysdvnpdusxdewvepqzutskveeuapsgjkipsvzjpmkidixftlxtlxavxusatynxxmpcezdimgakodifetecjlfcnoymjqcbbpbkvjfclswjtoadadfknocsjxjcwwbjxagpkzxyunavtqasvwclxapapwynizgvjdpxmmmxjluolistliyzxxdosttwqtnbzfsvnicfxlusvsydipcotvuvklsxalpyncmztjtmxbffggwyufqzpkfoppcnkwseqwpgiqugcooltepguectltjpzzqbtjgcpwljenwdfdegbzndgsppdgbdyvwpzfnsdntkicifmqcdcsifysyygkltipfnbnvwbmkiaxqebyyczgxbqbcoxtbuszlmnoxievxpbqyfzgxpbobtngbtteqwsnyifyzytyxuuamalwplwjiqlaelzxgvnoqaoiiszzzpljjvweaikfgqnysjouatbbvnncuqzywbkxdydquljudtnljzvdtidyjdppenkzfeluagvbwqgjumntydetfvxxqoviswxvupkugqajoldejvfgbpumgasdfoxmeboklcqkyclkodixgqbzdoyaqgtgcpnccwjjiqlxmulywsezklybibviukbwcvaqplpusgofygyxagikejncqcylgoujcgyavfzfvwlxnqflkyeambwmjlddaukuoeuiowqtytmogtncpupmucqfbmodifallypjdfdvbntvpsmcwcclazqvvnaezxpqdiycqqqavjxubfubwgjtddjgvkqkfpcqkkbsavnmtyxmjqexzxsixoawkniubbfkpmwcuvuutgnexaccdyunlaiwnvmzfqlznynvjenveeuvukqfbvjawlogauxqycwbopfkvoobqzzyjipsvbipdywsdoczubbwulywbbkigutamxekptqafwodvkazuwffxnolyjiademqqlezcxjypcs"
				+ "zn"
				+ "fjlovfvpzcgpnjdkcyftaeiadydtuckmblxgwzzspkvqewogmmpnzcvqjciiufazwzeibojpxzzcjcbbsudqymqjjcxzyntcmvkvqsqucljwnoveppifwpvgzigeo"
				+ "ypllwqsvanawmxutgzdanajuotmjqbsbttswjoapakfqaqtcwbgngpkalzfodnvzzzvpnnkqpijczcmwykjeceaxlgzmdytkpezbixfquoijkbczmapzubvzgcqoblqsieysuwkybajcxobodkmnsacbqqfmvkszpcbmasmtlqnxdfssqitfwntdpgxgunijpilceutvijqlfzgiplalvebajgflfsfljxaozypuoyutnyxkynxbexaycgiapfgseasppfgtliedjvzxfwggqgncgfulexizvuylyesvjpeualuxgtxzyijqjtcyovwzlokaxappbpuygpcadikzqqukjnppubvpgffxydzkkkzwdmoiazetyynndpmucqctmiyydfnglzlnpgaatzganeebtpvdpivpalksbxqbsjgtmmpadecixmumqfxitjgxtzudxdsaeambmkfqtvgfkvlbtwmogiwwskuqvsoboqgjqqtadmzfgjugssbnkywvwncjxbvsxedkjydzbcljcwlqzbxxozkvxvdajvzpctezgswfmfayqppazyzbxajwniwsmjnzyabamktejdiwaqubypjogfqofjmsqocckptaaoqjzmxtkzcwypxsyzubvvletysualpdxznqwselffciqknoovxpkjjcueddqcueqikxixlfjoacqjobgxikwupxxyoomtffzxkkqexugzxbdobeboeyzmlpqtfzivgifvtfavnnykxmmqwnoadbsvzpwfucwjpijqaxldndkktumwnzstynkfdyoxczgktcveloxssjuvjgafdqlwfkknyfzvzoxpovoqxteieynwsfmivlubssqnymqnqpwleadbmxiuvxecsdnqzugpknaekdmsgsmzvgnwvppknfgfnwckebwvezfouvzvwmvduaygifutjgiajbexbpalkvxgzgjmvzllosfqgtgpeuewweleovcvbzbvewadvntcefdwsxzbalckpyintivxmjtdofjgmgxvankautsvmepfjcyztsuaoaiyocwxeuxifpbmumqcnapwmbooxynjcmjdpzgsaawjlewugqvgssgebjydnifcwsmiqasaoagbdfswtknmopqbxbeqgdpawsqbztzkuwgqujvmcvmbvzftneckcydedlwakxoxavkvwyajigxzaonebzjvdbxycgimivjmumuqvoduiqxqpliymacgmgqwqevexxsosqdzudnxveyfjfbbabgtjbbtqusglbqncpeidlcnivewcnjbaocmvgaggojjocsgxxzdzxzbemvswslsmlmyyzlxcswmzoksglkvswppsknqsuyvxvxvzylwwffwoflietwefbtieopcuupxwsixdndfcnkpjbfnzdos"
				+ "xt"
				+ "euamltqpalcasstwswmxqmoclfeapvixuczdscwospabceqigswnbapgjmxinpcpopipdaousimpmmbofecpeqbvyjidexpxnpscneqcvkvgwlfxnlkdpzaiwyxnlflgeltpmueoqawygvwztxvwllmuojvnzgkmswmsooxjgujxqeatytugcjmkyinzwocyodadztgtcstunpbtboopjflivmmmqdwvqjiymfgczwkdeupjswagzyjliyusbjmpvamnubjnjxkzxyqfixbnddbnvjjamtisbqxctcolozvimkyqsiviyuypbtbltylukijupotidsgweqokqngyafxyqnipfpnbdtcealnjqdgmafytoozuqmqpqenquvveijdfzjktmejvjvpbemfjtoxmbzumoqkjzgulmdtnbnxsxxqpkocqmljgzowxxmosdxgnifggafivkalmaomzddkpfpsmqxnngfckysuuoqntwysjcvoslkbmvnmimpglunvotowxeqcsbxensxgyuouogytbdnlpuozkmimfvjjtsipxdvqflubedudnoxxsijszepqddkivgaqfeiojflaxpzgwyvnteykwysbojmuustydsilolbcoftntvaolpilsmbqudxnokdnpxtznqkwuybocdyzftybctakdydjcbwxcnpgeqpwykvcixfctgluieuimlnadfnpscjneyvaewlvjddcwdvzcsbozpzbpwqtdkqqbjcstwzxkjwpkajtzdgmnpxycpjtebosvdpnyubnqvengawgydunmqidicevnwbftscdemscyfbskemqpwdyksdogdgbiitjdcbionubnjfueflzjftielndlkmgfwodztmktacvjjtgngjkwmigkxexkvimwziyczkzziiyeemekktpsynotbxadwivnmsxymlollspzvpqwdgibglizco"
				+ "v"
				+ "nmklukoyvalmzeabscngpqcvdlquybvblgixdsidnunfpkuvistwwuafdaetjbvseidiigdixsnugxoenkbylibiqqwwemyfugnewfbeewaiobuvwxnlpjmltokdjpmnvjjljsumiomvddjvytwfkvjxqvmudxliuumybjticjnytxcnbjzlsgqsmqglnczwpwjedwqnslgacazexlnplmlvopcomtudmazuwusaegzmtoycoyuouwcwvygfjlqewjlkfpygwmoozkekdosyeqbonqkmytzgqzfdavfyscukszdiuwjokozziejsdabjijnbjsyqgjsiiqsgnaiynwjxmfatbvfqxontyufffcatpmozeankmluzqgqemzxvtcwlsvqexigymoaymjlnbebxuzclvpsmysqbqayqkvcfulwsmnzkxiabltqubsjwtxmktdwkxdemmiepfnzflesdpstlzcssoqzquvunfwgkzeunpnfcoiuongiuudaueodatfljzutksmzqqmydtoutyocjcvcmbpdpijypxudllnkxldmuejmffqmgdiyfzsnabwqyuwynxmotejtclplkwyioaifpzmkakqjkjxbtzaeidnupozcplsuvngotuccmadqpsueiilgxsuqaqgjpyczksbu"
				+ "txutjppglrtnzalurrfcggoaoirnhtlcijpuguuselgviabyvyosfkmnbipvkfgvoxlsuaviqarhnnsuusbbzfvpujqlmkuisresqulurnildhnfwdxnoqamnagacxfvoxbfpdmldsvzbxftazejbymarmwcofaeeaulteyvibohnnjlpulukjaaofitqqwmeclleysohgecxlcyncshhfmlrhtedelxerslxbxnwefbhlmzpmlaavzgnhelqlxlzhsygwtypkddzxqhqhhbvuuunbbdrcwrtiinediiwkvpejcpggbuuquroowiyqyyvseewxrnbzglvfsztyibmqfedvmaxxbellnfkapgahsqlvwgooiqebxdechaaunhpuusaxsdwcxhktctjpmnsbcueqzjfgfzdgutxrgsfmvvnlqgvlrkswfuzvvdbyxgnrtzdntrzjfjumyxkqrvlvhcwxxuiuaxuujswraltehnjqhdsxuzpuzirufvkmpvowqrqzdpehlnbjrpdyvnwbppokhbpogmjcsorbxkxsboosusmeedhomdjqlwroiqgxjsxrndydoiuvalcuzwcpcnakbocqrwqmrwbdhdblbbfdphnwcyxnfaqhzneqnyzuqucdlotlrhrsvxlzpfkgibnnkpanowscjtscnmnytcgmuxeadiefprcnwxpfrdzkvpxftqqwbaigdcngbwizjnjqaadgjnfudkdufkdyeoomftggkinjedtfjflnooqzhjhqvtwgllrsbroyupckgwcmspfmuxbtfryqtozopielccbqfztwpuubclxbjdqfoyhgowxotkeuyscosvflrpxutfdmcalcferakrcpbsrwogadcruvdptosljltklrwvciyleuufrndiubrlghusgspecbjuplacndwppyyljwwbgzoljmhykoyhnkafixhekiovxhxqwnefvitryhiemuyzuhxtogkmvpcuviojnuxawxlifdmgnhczwfcrmgbyowybphxkgtmwdgivakywfbmmhjutuqvarjbcxivapjzqvnzxnuldgbymgbbuacbbntnihsbtdcjgnbmrywjunctygurcyrhnszxkiryaamorpbrqvfmlgfntryijclrdquamhuzaizhjzdqbkvyexwochtovsrsngmnjgzcjaehwfsnzrfxposuzpqlwfsskbatljohqdmddbpvojszrfmtnncjibvnjylpeyxzqfsrjdfetaxymhoqvuitgveaoocnaynpeksxtpwnongwwprfjhyzxbiqxa"
				+ "isxozzjoxqcmnczzuacabkedboxqexfalcwizbjvejylzsccuojknwnoyktdvwysfgvwbllwqaivubwjkofnmiyaepfxpmyoaotnvlmckjumojyvagxcuzukxsfdcvnslcwtgfwoyaciosdeuouidgjxisatjygfkxdxfwkapidutbsstzwluxggtoluzgvmelcsdfkgkjvpainlegwmbjkaxxxipxybscxkvnevmzmooyjnnpxsjabkyokbalsfeoqkaamooljwusdbdtqnbxxjugkuinelautwdiwtbpezaxzmminfypjebzkgmuyfiyoecdaswtsisxmbekuqlvsitdkpzyspdtdovcmgcelektiaembusmacixjpnynqwsvsqpvaoaatsjgemmulytoglkvkvsiqzcwzednayfwznljbcezpdpqfqlsabfxpbvtvktzwgpubszpmbtxosuqtpixgpneuqemmugunpvbexgzqmpbjgpfkjtfdcadlnfdnyvmncqxdjtflmcbfmvigksnlvmkytbkegottzftjsctpbcyfstwsujdmyzctywzndgyzduwxoavusuugaalucmgcplfgnofawqqplwbounedvmpeulaofnydmkzanxjuzxzgvlofmuuuplbwzsuggpaxdyitqkcgnulgexcyduyzkfjmunqdydggcvoamnxtaiivoupbogtskaalfnkkygpkfwxnulelqjzipmnldilnztxeajobdwziicdqmckdypbsdlqmjmxvkbknjogyaqnblmbbdifbvmwxjagnlvilkplabvpdievwqaqxzqlndoaowldpeoqpwvqbdvywcvlnafgnmvftotgcgtvykajbmstpzuvmxoqtzntddddgadzfgpbvitfxsutiayeulatcaqykpdnixwwfslskckjmfkxxpymvkzjekbjqfavqwlvxtiyugqyaqvkzvbglbjmtyjpwycxllpoklnpkjutqkkndxzubivtdvlysxbgpakxdfgwoslsbjyilxesvuwzmdclvaavijyaliauwwiflexlwbnibpaibvuacwnkgmmmgeegjgyjfimycioqzyevjmfeaqfityvlbyuslepwxuemqxfktjoynmibqkbfcmnqtagdvpdwutoqbysemydfxxnuvvcdwefgcieufzakfbojiitzukfskzxqyxwxyvlbtmsyveixvdxffqwjnektgbyiawlsfnfycttfwvvpfmdbqfidcipmbnznzdzceetcppbpomvwfyxiitkacvxwoefvfqtxuwpzlegoqesekxbqubeqspvxitxyfvfzoxlcngxzgiqkiblwvwvfgyuuptxassebzybwjmvunlazzokkgfknunqp"
				+ ""
				+ "igwhrqnbclmucukpsfcactxwejmgdaalarswxcxrbyijtglvhridvrbiwoblwmxsdpclutrktryhbpgwsmgpcnihktwostxsalkpiwzsllfkfejahfvgteqjdseatsneubzdyxgneibidelubhlqjuxspvckaewesurueileokxhaltfcygzmzfoayxflpsmnkaqwvrpghymlyejhcclmpdhgearxlymdmomfywlizjznnpvrvysgugwqiwyhnhihlnakfpfxikjuxrooympxappulnhgenhxzvcsratkxoqrfonkfemhmjxuimkgbhetvlpclbgjajvkojdkvdrqesnnssguzirieiidvixdonsdzapznvzoxhkfmsbpybpwveuiydnlwtrssykndjnhrgwvgyzdoiedupkidepifvccvssmcxmdfbixevmuifiekeecywhszdysltzcjehfmgdwdmwglgdlzytstvqagvlkyubetaydvijsdbgsehacpkpireiociaajrztokojjbdhrhmfosnnsyhkcycuaopjelyhcasmtjcpuspfpafnbiullrfpdthitpfralijcmxirsoscqpfofdsyazzqrvsjmkhdccqkaiowyszjiliourypatpjqfsopclyusuafayjyyvaxlszrjptsmmbztayxitjrscsjfwptadnoorbkehcfatapkgxsovaaddqynhidboffchlugrxylpqfkzcngumkgdaeupygvnsdvloeufejriqfglxmxkosyaystkeylhjfbnivwhgsbvatxxunebkbtksgbczkchveaqhmyhirxoldofmgscznztxojmhnoppuvmhlivbwfolruihocvakrsywctjiaxzyhmotghvedxmmjptbyvilowtmwvqolksyvhyluhlrdbbotxkrfhjbrrlrppwolcalmgnnotrtjrhtkdmlsbvgufjzbjirnywxiixwiojptfhdmdafkgeulcsgwujzlwhqwxhywkoitiqiziutgacfpmegercmfetmivrsonxeaebidbhpqylqkzczyxbjcgdbsthhjouqfgrmpriqoyupgqrtjwppfawyujzzkvwfjmquuqsqjidtenykwdkwkvnybothjqdsppamgpvfsphlvmnyleknxstvxjilbodeklpnuyjcdxkeqxmwoynxzxtctswpfagwensxjxeknnqmadnxjqviqrjrujdimtvwcuhssvmwsztfeirngcorckgvvaxicvmpxrhuxnmxnrlpfqeoseisxvwfcmugqhilutrludkkbbttxftasuqxjkscffkuumsimwfrkkublqgleaacfegzrttmdkdqttktnyvboqqeamukehhgmrdyqucgqmahkfbnjpmjubmopkgqgnqobwmpbeszvoivwduussdrftiulprjsnfptrscvyezuzatxcepacjaxfbrhiwcvvkoybpamzniwvobdsoqnbfhqmikeffezqelyqtxltobisjgwtvbohbxpenmiewbqljhtmhuasyhtnpyeknsarkoereicozykhgetduolfjjhvovgga"
				+ "j"
				+ "tbundbxwpxgxggkayfzccdylaulcwtnjklwxyeucnbwfidlddvnsgxzfaeklgqqnpyolzfswepzddtomvlojfydumzzzomyviuztkgsyulyfbptemzstfxmo"
				+ "lmefkfdjbifmiwbutaikocygnpmjuwnzigdvzslmcljcwlmoyoppqvopvojdcejnbdpifnocsaqsbvybqmwflkiwgwfvpexpaloesyqdcblwkpclwjzjpslxlluibawmnfatqjatcvbuauoldkixjdkymzgaoegytnqafcpagjissallazotfedgpgvqs"
				+ "eslnzxujanukzoztqvmqzwjwwmbtpmpbbupnfaklagyaacpuoqamlagmsj";
		System.out.println(stackString(s));
	}
	
	/*static String hackerrankInString(String str) {
		
		// return StackString(str);
        
		int index = str.indexOf("h");
		str = str.substring(index, str.length()).replaceAll("[^h|^a|^c|^k|^r|^n|^e]", "");
		return findHackerRank(str);
    }*/

	private static String stackString(String str) {
		// Complete this function
		
        return str.matches(".*h.*a.*c.*k.*e.*r.*r.*a.*n.*k.*")?"YES":"NO";
	}
	
/*	static String findHackerRank(String str) {
		
		StringBuilder builder = new StringBuilder(str);
		StringBuilder result = new StringBuilder();
		result.append(builder.charAt(0));
		for (int i = 1; i < builder.length(); i++) {
			char firstChar = builder.charAt(i);
			StringBuilder temp = new StringBuilder(result);
			temp.append(firstChar);
			boolean existed = checkConstaint(temp.toString());
			if(existed) {
				result.append(firstChar);
				if("hackerrank".equals(result.toString())) {
					return "YES";
				}
			}
		}
		return "NO";
	}*/
	
	/*static boolean checkConstaint(String s) {
		boolean flag = false;
		switch (s) {
		case "h":
		case "ha":
		case "hac":
		case "hack":
		case "hacke":
		case "hacker":
		case "hackerr":
		case "hackerra":
		case "hackerran":
		case "hackerrank":
			flag = true;
		break;
		default:
			flag = false;
		}
		return flag;
	}*/
}
